# Generated by Django 4.2.20 on 2025-11-06 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigiUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('last_connected_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='DigiPass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pass_type', models.CharField(max_length=50)),
                ('point_power', models.PositiveIntegerField(default=2)),
                ('card', models.ImageField(upload_to='ntfpass')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('scored_point', models.PositiveBigIntegerField(default=0)),
                ('referrals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text="The user's connected wallet address", max_length=42)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('minted', models.BooleanField(default=False)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_paid_bnb', models.DecimalField(decimal_places=8, help_text='Amount of BNB paid', max_digits=18)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the transaction has been verified on-chain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_upgrade', models.BooleanField(default=False)),
                ('digipass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.digipass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
