# Generated by Django 4.2.20 on 2025-11-11 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField(default=10)),
                ('task_type', models.CharField(choices=[('on_site', 'On-Site'), ('off_site', 'Off-Site')], max_length=50)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referrals',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_pass_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=4325, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-scored_point'], name='main_profil_scored__5196ab_idx'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usertaskcompletion',
            unique_together={('user', 'task')},
        ),
    ]
