# Generated by Django 4.2.20 on 2025-12-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginnonce_alter_profile_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_pass_power',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.digipass'),
        ),
        migrations.AlterField(
            model_name='passtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='passtransaction',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the transaction has been verified on-chain'),
        ),
        migrations.AlterField(
            model_name='passtransaction',
            name='minted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='passtransaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scored_point',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='passtransaction',
            index=models.Index(fields=['user', 'is_verified', 'minted', '-created_at'], name='main_passtr_user_id_bb1c82_idx'),
        ),
        migrations.AddIndex(
            model_name='passtransaction',
            index=models.Index(fields=['tx_hash'], name='main_passtr_tx_hash_25880e_idx'),
        ),
    ]
