# Generated by Django 4.2.20 on 2025-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_current_pass_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
