# Generated by Django 4.2.20 on 2026-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_icon_usertaskcompletion_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainListenerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_processed_block', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('log_index', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('tx_hash', 'log_index')},
            },
        ),
    ]
