# Generated by Django 4.2.20 on 2026-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blockchainlistenerstate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedEvent',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
