# Generated by Django 4.2.20 on 2026-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_avatar_url_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestnetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('invite_link', models.CharField(blank=True, max_length=500, null=True)),
                ('member_count', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=200, unique=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('faucet_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
