# Generated by Django 4.2.20 on 2026-06-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_referral_code'),
        ('main', '0007_add_avatar_url_to_profile'),
    ]

    operations = [
    ]
