# Generated by Django 4.2.20 on 2026-07-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20260616_0417'),
        ('main', '0008_testnetapplication'),
    ]

    operations = [
    ]
